### ISSUE TITLE
Suggestion: add default values to some fields

### ISSUE THREAD

**Issue by rmmariano** [brazil-data-cube/bdc-catalog#137]
Leave the fields `collection_type`, `is_public` and `version` accept a default value when the registration is done. For example:

```
ALTER TABLE bdc.collections ALTER COLUMN collection_type SET DEFAULT 'collection';
ALTER TABLE bdc.collections ALTER COLUMN version SET DEFAULT 1;
ALTER TABLE bdc.collections ALTER COLUMN is_public SET DEFAULT FALSE;
```

This would facilitate the insertion of records.

Thank you in advance.

**Comment by raphaelrpl** [comment]
Resolved in v1.0-alpha1
