### ISSUE TITLE
Suggestion: rename fields

### ISSUE THREAD

**Issue by rmmariano** [brazil-data-cube/bdc-catalog#139]
I would like to suggest renaming some fields:

(1) In the `collections` table, rename `extent` to `spatial` or `extent_spatial` to make it more similar to the [STAC specification](https://github.com/radiantearth/stac-spec/blob/v0.9.0/collection-spec/collection-spec.md#extent-object), because there is both the `extent spatial` and` extent temporal`.

(2) In the `collections` and` items` tables, rename the `created` and` updated` fields to `created_at` and` updated_at` to make the type of fields more explicit, because leaving only `created` and `updated` , it sounds they are flags (i.e. boolean fields), while the suffix `_at` makes them explicit that they are dates.

**Comment by gqueiroz** [comment]
We will named this collection: spatial_extent
